# docker-compose.test.yml
version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - USE_HTTPS=false
    volumes:
      - ./gateway:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - MONGO_URI=mongodb+srv://${MONGO_USER}:${MONGO_PASS}@${MONGO_CLUSTER}/pgpaal_auth_service?retryWrites=true&w=majority

    volumes:
      - ./auth-service:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

networks:
  default:
    name: pgpaal-test-network